
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 04 18:11:31 MST 2022
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OpAgrup_LlaveApert = 62;
  public static final int PR_GetAngle = 13;
  public static final int OpLog_Not = 57;
  public static final int PR_Exeption = 10;
  public static final int Op_Decremento = 54;
  public static final int PR_UpLeg = 35;
  public static final int PR_TurnRight = 32;
  public static final int OpLog_Or = 56;
  public static final int PR_GetPosition = 14;
  public static final int PR_Catch = 2;
  public static final int OpRel_Mayor = 48;
  public static final int PR_Default = 5;
  public static final int PR_Option = 22;
  public static final int SimbEsp_Coma = 72;
  public static final int OpRel_Diferente = 52;
  public static final int PR_False = 40;
  public static final int OpRel_MayorIgual = 51;
  public static final int OpAritm_Resto = 46;
  public static final int PR_UpArm = 34;
  public static final int SimbEsp_Punto = 71;
  public static final int SimbEsp_Comilla = 70;
  public static final int OpAgrup_LlaveCierre = 63;
  public static final int PR_Rotate = 24;
  public static final int OpAritm_Resta = 43;
  public static final int PR_Word = 38;
  public static final int PR_Class = 3;
  public static final int PR_DownLeg = 7;
  public static final int PR_Interruption = 17;
  public static final int PR_SetMotor = 26;
  public static final int PR_Def = 4;
  public static final int PR_Move = 21;
  public static final int PR_While = 37;
  public static final int ERROR5 = 79;
  public static final int ERROR4 = 78;
  public static final int Numero_Exact = 69;
  public static final int ERROR3 = 77;
  public static final int ERROR2 = 76;
  public static final int ERROR1 = 75;
  public static final int OpAgrup_CorchApert = 60;
  public static final int OpRel_Igual = 49;
  public static final int PR_Stop = 29;
  public static final int PR_Part = 23;
  public static final int PR_TurnLeft = 31;
  public static final int Simbolo_Especial = 74;
  public static final int OpAritm_Mult = 44;
  public static final int SimbEsp_DosPuntos = 73;
  public static final int PR_DownArm = 6;
  public static final int OpAritm_Div = 45;
  public static final int PR_SetAngle = 25;
  public static final int OpAgrup_ParApert = 58;
  public static final int OpRel_Menor = 47;
  public static final int PR_Motor = 20;
  public static final int EOF = 0;
  public static final int OpAritm_Suma = 42;
  public static final int OpAgrup_ParCierre = 59;
  public static final int PR_For = 12;
  public static final int PR_True = 39;
  public static final int OpLog_And = 55;
  public static final int PR_Speed = 28;
  public static final int OpAsig = 64;
  public static final int PR_If = 15;
  public static final int PR_Try = 30;
  public static final int PuntoComa = 65;
  public static final int PR_Flag = 11;
  public static final int error = 1;
  public static final int PR_Void = 36;
  public static final int PR_Ing = 16;
  public static final int PR_Else = 8;
  public static final int PR_Switch = 33;
  public static final int Identificador = 66;
  public static final int PR_SetPosition = 27;
  public static final int PR_Return = 41;
  public static final int PR_Exact = 9;
  public static final int PR_Imp = 18;
  public static final int OpAgrup_CorchCierre = 61;
  public static final int Op_Incremento = 53;
  public static final int PR_Main = 19;
  public static final int Numero_Part = 68;
  public static final int OpRel_MenorIgual = 50;
  public static final int Cadena_texto = 67;
}

