
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 03 22:23:11 MST 2022
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PR_Flag = 9;
  public static final int PuntoComa = 50;
  public static final int PR_False = 25;
  public static final int PR_Exact = 7;
  public static final int PR_Return = 26;
  public static final int OpRel_Menor = 32;
  public static final int PR_Word = 23;
  public static final int OpAsig = 49;
  public static final int PR_Catch = 2;
  public static final int OpAgrup_ParCierre = 44;
  public static final int PR_Default = 5;
  public static final int OpRel_Mayor = 33;
  public static final int Simbolo_Especial = 59;
  public static final int OpAgrup_LlaveApert = 47;
  public static final int OpAritm_Suma = 27;
  public static final int OpLog_Not = 42;
  public static final int OpLog_And = 40;
  public static final int Op_Incremento = 38;
  public static final int PR_Switch = 20;
  public static final int OpAritm_Div = 30;
  public static final int PR_For = 10;
  public static final int OpAgrup_CorchCierre = 46;
  public static final int ERROR5 = 64;
  public static final int ERROR4 = 63;
  public static final int ERROR3 = 62;
  public static final int ERROR2 = 61;
  public static final int ERROR1 = 60;
  public static final int Op_Decremento = 39;
  public static final int OpRel_MenorIgual = 35;
  public static final int PR_Ing = 12;
  public static final int Numero_Part = 53;
  public static final int OpAgrup_CorchApert = 45;
  public static final int PR_Main = 15;
  public static final int EOF = 0;
  public static final int SimbEsp_Coma = 57;
  public static final int error = 1;
  public static final int PR_Class = 3;
  public static final int OpRel_MayorIgual = 36;
  public static final int PR_True = 24;
  public static final int OpAritm_Resto = 31;
  public static final int OpLog_Or = 41;
  public static final int Numero_Exact = 54;
  public static final int PR_Imp = 14;
  public static final int PR_Try = 19;
  public static final int PR_Void = 21;
  public static final int OpAgrup_ParApert = 43;
  public static final int SimbEsp_Comilla = 55;
  public static final int PR_Exeption = 8;
  public static final int PR_Part = 17;
  public static final int OpAritm_Resta = 28;
  public static final int PR_Else = 6;
  public static final int PR_Stop = 18;
  public static final int SimbEsp_Punto = 56;
  public static final int Identificador = 51;
  public static final int PR_Interruption = 13;
  public static final int OpRel_Igual = 34;
  public static final int OpAgrup_LlaveCierre = 48;
  public static final int PR_If = 11;
  public static final int OpAritm_Mult = 29;
  public static final int PR_While = 22;
  public static final int Cadena_texto = 52;
  public static final int PR_Option = 16;
  public static final int SimbEsp_DosPuntos = 58;
  public static final int PR_Def = 4;
  public static final int OpRel_Diferente = 37;
}

